# Generated by Django 2.2.6 on 2019-11-03 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('ethnicity', models.CharField(max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('PAL', models.IntegerField(default=0)),
                ('blood_p', models.IntegerField(default=0)),
                ('AIPW', models.IntegerField(default=0)),
                ('SIPW', models.IntegerField(default=0)),
                ('smoker', models.BooleanField(default=False)),
                ('hearthbeat', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prof.Doctor')),
            ],
        ),
    ]
