# Generated by Django 2.2.6 on 2019-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191103_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='blood_p',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
