# Generated by Django 2.2.6 on 2019-12-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191103_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='doctor',
        ),
    ]
